import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Navbar from "./components/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex border border-red-700 h-screen w-screen">
          {/* LEFT */}
          <div className="w-[10%] border flex flex-col items-center m-2">
            <Image src="/Large-logo-no-bg.png" alt="" width={40} height={40} />
            <Navbar />
          </div>
          {/* RIGHT */}
          <div className='border w-[90%] flex-col justify-between '>
            <div>
              <h1>Kindgdom Security</h1>
              <FontAwesomeIcon icon="fa-solid fa-house" />
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
